dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.0.0
  latlong2: ^0.9.0
  geolocator: ^13.0.1
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/lucknow_network.geojson

