

name: railway_app
description: A new Flutter project
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Map + GeoJSON
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Location services
  geolocator: ^13.0.1

  # Blue GPS dot on flutter_map (new version compatible with flutter_map 7 + geolocator 13)
  flutter_map_location_marker: ^9.1.1
  # State management (optional, helps avoid setState issues)
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lucknow_network.geojson
