
name: railway_app
description: A mobile app for railway OHE cable visualization in Lucknow
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # Maps & Location
  flutter_map: 7.0.2
  latlong2: ^0.9.0
  geolocator: ^13.0.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lucknow_network.geojson


