name: apprail
description: A Flutter railway route visualization and OHE monitoring app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Map & Location
  flutter_map: ^7.0.2
  latlong2: ^0.9.0

  # Real-time location marker for flutter_map
  flutter_map_location_marker:
    git:
      url: https://github.com/tlserver/flutter_map_location_marker.git
      ref: master

  # GPS & Geocoding
  geolocator: ^11.0.0
  geocoding: ^2.2.0

  # Networking (for API requests if needed)
  dio: ^5.4.0

  # Search bar / auto-suggest
  flutter_typeahead: ^5.2.0

  # UI Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/geojson/lucknow_network.geojson
    - assets/images/
