name: apprail
description: A Railway Cable Route Visualization App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Map core
  flutter_map: ^6.2.1
  latlong2: ^0.9.0

  # Show current location
  flutter_map_location_marker: ^8.0.3

  # GPS + Geocoding
  geolocator: ^11.0.0
  geocoding: ^2.2.0

  # Search & API calls
  dio: ^5.4.0
  flutter_typeahead: ^5.2.0

  # UI
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/geojson/lucknow_network.geojson
    - assets/images/

