name: railway_app
description: Railway OHE Map for Lucknow
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Map rendering
  flutter_map: ^8.2.1
  latlong2: ^0.9.0

  # Location services
  geolocator: ^14.0.2
  flutter_map_location_marker: ^10.1.0

  # HTTP for fetching GeoJSON or APIs
  http: ^1.2.2

  # State management (optional but recommended)
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lucknow_network.geojson

