name: apprail
description: A Railway Route and OHE Pole tracking app for Lucknow Division demo.
publish_to: "none" # Remove this if you want to publish on pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Mapping
  flutter_map: ^7.0.2
  google_maps_flutter: ^2.9.0
  latlong2: ^0.9.0

  # Location & geocoding
  geolocator: ^11.0.0
  geocoding: ^2.2.0

  # Networking
  dio: ^5.4.0

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # If you have assets (GeoJSON, KML, images)
  assets:
    - assets/geojson/
    - assets/images/

